name: 'Build wheels for macOS'
description: 'Build wheels for macOS'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'
runs:
  using: 'composite'
  steps:
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tools/requirements-macos.txt
      shell: bash

    - name: Build wheel
      run: |
        cd ${{ github.workspace }}
        rm -rf build
        mkdir -p build dist
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
        cmake --build build
      shell: bash
